import React from 'react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { AIAnalysisResult } from '../types';
import CyberButton from './CyberButton';

interface SecurityReportProps {
  result: AIAnalysisResult;
  password: string;
}

const SecurityReport: React.FC<SecurityReportProps> = ({ result, password }) => {
  const generatePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    
    // -- PDF Design --

    // Background for Header
    doc.setFillColor(2, 6, 23); // slate-950
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    // Title
    doc.setTextColor(34, 197, 94); // green-500
    doc.setFontSize(22);
    doc.setFont('courier', 'bold');
    doc.text('PASSWORD SECURITY', 14, 20);
    doc.text('HEALTH REPORT', 14, 30);
    
    // Header Meta Data
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    const dateStr = new Date().toLocaleString();
    doc.text(`GENERATED: ${dateStr}`, pageWidth - 14, 20, { align: 'right' });
    doc.text(`REF ID: ${Math.random().toString(36).substring(7).toUpperCase()}`, pageWidth - 14, 28, { align: 'right' });

    // Calculate Next Check Date (30 days from now)
    const nextCheck = new Date();
    nextCheck.setDate(nextCheck.getDate() + 30);
    
    // -- Data Tabulation --
    
    const tableBody = [
      ['Target Credential', password],
      ['Security Score', `${result.score}/100 (${result.score < 50 ? 'CRITICAL' : result.score < 70 ? 'MODERATE' : 'SECURE'})`],
      ['Analysis Date', dateStr],
      ['Next Recommended Audit', nextCheck.toLocaleDateString()],
      ['Detected Patterns', result.similarPatterns.length > 0 ? result.similarPatterns.join(', ') : 'None Identified'],
      ['Breach Probability', result.breachProbability]
    ];

    // Table 1: General Info
    autoTable(doc, {
      startY: 50,
      head: [['METRIC', 'DETAILS']],
      body: tableBody,
      theme: 'grid',
      headStyles: { 
        fillColor: [2, 6, 23], 
        textColor: [34, 197, 94], 
        lineColor: [34, 197, 94], 
        lineWidth: 0.1,
        font: 'courier',
        fontStyle: 'bold'
      },
      bodyStyles: { 
        fillColor: [10, 10, 10], 
        textColor: [220, 220, 220], 
        lineColor: [50, 50, 50], 
        lineWidth: 0.1, 
        font: 'courier' 
      },
      alternateRowStyles: { fillColor: [5, 20, 10] }
    });
    
    // -- Vulnerabilities & Strengths Table --
    
    const yPos = (doc as any).lastAutoTable.finalY + 15;
    
    doc.setFontSize(14);
    doc.setTextColor(34, 197, 94);
    doc.setFont('courier', 'bold');
    doc.text('VULNERABILITY ASSESSMENT', 14, yPos);
    
    const weaknessRows = result.weaknesses.map(w => ['WEAKNESS', w]);
    const strengthRows = result.strengths.map(s => ['STRENGTH', s]);
    const vectorRows = result.attackVectors.map(v => ['VECTOR', v]);
    
    // Add placeholders if empty
    if (weaknessRows.length === 0) weaknessRows.push(['WEAKNESS', 'None Detected']);
    if (strengthRows.length === 0) strengthRows.push(['STRENGTH', 'None Detected']);
    if (vectorRows.length === 0) vectorRows.push(['VECTOR', 'None Specific Detected']);

    const assessmentBody = [...weaknessRows, ...vectorRows, ...strengthRows];

    autoTable(doc, {
      startY: yPos + 5,
      head: [['TYPE', 'OBSERVATION']],
      body: assessmentBody,
      theme: 'grid',
      headStyles: { 
        fillColor: [20, 0, 0], 
        textColor: [239, 68, 68], 
        lineColor: [239, 68, 68], 
        lineWidth: 0.1,
        font: 'courier',
        fontStyle: 'bold'
      },
      bodyStyles: { 
        fillColor: [10, 10, 10], 
        textColor: [220, 220, 220], 
        lineColor: [50, 50, 50], 
        lineWidth: 0.1, 
        font: 'courier' 
      },
      columnStyles: {
        0: { fontStyle: 'bold' }
      },
      didParseCell: function(data) {
        if (data.section === 'body' && data.column.index === 0) {
            const type = data.cell.raw;
            if (type === 'WEAKNESS') data.cell.styles.textColor = [239, 68, 68]; // Red
            if (type === 'VECTOR') data.cell.styles.textColor = [249, 115, 22]; // Orange
            if (type === 'STRENGTH') data.cell.styles.textColor = [34, 197, 94]; // Green
        }
      }
    });

    // -- Footer --
    const finalY = (doc as any).lastAutoTable.finalY + 20;
    
    doc.setDrawColor(34, 197, 94);
    doc.setLineWidth(0.1);
    doc.line(14, finalY, pageWidth - 14, finalY);

    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('This automated security audit is generated by the Password Strength Problem Platform.', 14, finalY + 5);
    doc.text('Confidentiality: This document contains sensitive credential analysis.', 14, finalY + 9);
    doc.text('Disclaimer: For educational and testing purposes only.', 14, finalY + 13);

    doc.save('Security_Health_Report.pdf');
  };

  return (
    <div className="w-full mt-8 animate-in fade-in slide-in-from-bottom-8 duration-700">
      <div className="relative bg-slate-950 border border-green-500/30 p-1 rounded-xl overflow-hidden group hover:border-green-500/60 transition-all shadow-lg">
        {/* Animated Background Gradient */}
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-green-900/20 via-slate-950 to-slate-950 opacity-50"></div>
        
        <div className="relative p-6 flex flex-col md:flex-row items-center justify-between gap-6 backdrop-blur-sm">
            <div className="flex items-start gap-4">
                <div className="p-3 bg-green-500/10 rounded-lg border border-green-500/20 text-2xl">
                    📊
                </div>
                <div>
                    <h3 className="text-green-400 font-bold uppercase tracking-widest text-sm flex items-center gap-2 mb-1">
                        <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse shadow-[0_0_10px_rgba(34,197,94,0.8)]"></span> 
                        Security Health Report Ready
                    </h3>
                    <p className="text-xs text-green-500/60 font-mono max-w-sm leading-relaxed">
                        Full audit analysis complete. Includes breach probability, attack vectors, and pattern matching data.
                    </p>
                </div>
            </div>
            
            <CyberButton 
                onClick={generatePDF}
                className="w-full md:w-auto min-w-[200px] shadow-[0_0_20px_rgba(34,197,94,0.1)] hover:shadow-[0_0_30px_rgba(34,197,94,0.3)]"
            >
                <div className="flex flex-col items-center leading-none py-1">
                    <span className="text-xs uppercase opacity-70 mb-1">Export PDF</span>
                    <span className="font-bold">DOWNLOAD REPORT</span>
                </div>
            </CyberButton>
        </div>
      </div>
    </div>
  );
};

export default SecurityReport;